name: Pull Request

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  check-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install @octokit/rest @actions/core

      - name: Download and extract TruffleHog
        shell: bash
        run: |
          wget https://github.com/trufflesecurity/trufflehog/releases/download/v3.40.0/trufflehog_3.40.0_linux_amd64.tar.gz
          tar -xzf trufflehog_3.40.0_linux_amd64.tar.gz
          sudo mv trufflehog /usr/local/bin/

      - name: TruffleHog secret scan
        shell: bash
        run: |
          trufflehog git file://./ --since-commit ${{ github.event.repository.default_branch }} \
            --branch HEAD --fail --no-update --json --no-verification > secrets.json

      - name: Trufflehog PR commenter
        id: hello
        uses: therealdwright/trufflehog-secrets-detector@v1.0.0
        with:
          secrets-file: secrets.json
